name: CallSMSBlock

options:
  developmentLanguage: pt-BR
  
  deploymentTarget:
    iOS: 16.0

packages:
  PhoneNumberKit:
    url: https://github.com/marmelroy/PhoneNumberKit
    exactVersion: 4.0.0

configs:
  Development: debug
  Production: release

targets:
  ################################
  # Call Directory extension
  ################################
  CallDirectory:
    type: app-extension
    platform: iOS
    configFiles:
      Development: CallDirectory/Config/dev.xcconfig
      Production: CallDirectory/Config/dev.xcconfig
    settings:
      TARGETED_DEVICE_FAMILY: 1
      ONLY_ACTIVE_ARCH: YES
      DEVELOPMENT_TEAM: $(DEVELOPMENT_TEAM)
      CODE_SIGN_IDENTITY: iPhone Distribution
      CODE_SIGN_STYLE: Manual
      PROVISIONING_PROFILE_SPECIFIER: $(PROVISIONING_PROFILE_SPECIFIER)
      SWIFT_VERSION: $(SWIFT_VERSION)
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      CURRENT_PROJECT_VERSION: $(CURRENT_PROJECT_VERSION)
      OTHER_LDFLAGS: ["$(inherited)", -ObjC]
      FRAMEWORK_SEARCH_PATHS: ["$(inherited)", "$(PROJECT_DIR)"]
    sources: [CallDirectory, CallSMSBlock/Core/Shared]
    info:
      path: CallDirectory/Config/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleIdentifier: $(BUNDLE_IDENTIFIER)
        CFBundleDisplayName: $(PRODUCT_NAME)
        ENVIRONMENT: $(ENVIRONMENT)
        NSExtension: {
          NSExtensionAttributes: {
            CXCallDirectoryEnabled: YES
          },
          NSExtensionPointIdentifier: "com.apple.callkit.call-directory",
          NSExtensionPrincipalClass: "$(PRODUCT_MODULE_NAME).CallDirectoryHandler"
        }
    entitlements:
      path: CallDirectory/CallDirectory.entitlements
      properties:
        com.apple.security.application-groups: [
          "group.br.com.test.call.block.CallSMSBlock"
        ]

  ################################
  # MessageFilter
  ################################
  MessageFilter:
    type: app-extension
    platform: iOS
    configFiles:
      Development: MessageFilter/Config/dev.xcconfig
      Production: MessageFilter/Config/dev.xcconfig
    settings:
      TARGETED_DEVICE_FAMILY: 1
      ONLY_ACTIVE_ARCH: YES
      DEVELOPMENT_TEAM: $(DEVELOPMENT_TEAM)
      CODE_SIGN_IDENTITY: iPhone Distribution
      CODE_SIGN_STYLE: Manual
      PROVISIONING_PROFILE_SPECIFIER: $(PROVISIONING_PROFILE_SPECIFIER)
      SWIFT_VERSION: $(SWIFT_VERSION)
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      CURRENT_PROJECT_VERSION: $(CURRENT_PROJECT_VERSION)
      OTHER_LDFLAGS: ["$(inherited)", -ObjC]
      FRAMEWORK_SEARCH_PATHS: ["$(inherited)", "$(PROJECT_DIR)"]
    sources: [MessageFilter]
    info:
      path: MessageFilter/Config/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleIdentifier: $(BUNDLE_IDENTIFIER)
        CFBundleDisplayName: $(PRODUCT_NAME)
        ENVIRONMENT: $(ENVIRONMENT)
        NSExtension: {
          NSExtensionAttributes: {
            ILMessageFilterExtensionNetworkURL: "https://api-dev.callspam.org/call-report2"
          },
          NSExtensionPointIdentifier: "com.apple.identitylookup.message-filter",
          NSExtensionPrincipalClass: "$(PRODUCT_MODULE_NAME).MessageFilterExtension"
        }
    entitlements:
      path: MessageFilter/MessageFilter.entitlements
      properties:
        com.apple.developer.associated-domains: [
          "messagefilter:api-dev.callspam.org"
        ]
        com.apple.security.application-groups: [
          "group.br.com.test.call.block.CallSMSBlock"
        ]

  ################################
  # UnwantedComunication
  ################################
  UnwantedComunication:
    type: app-extension
    platform: iOS
    configFiles:
      Development: UnwantedComunication/Config/dev.xcconfig
      Production: UnwantedComunication/Config/dev.xcconfig
    settings:
      TARGETED_DEVICE_FAMILY: 1
      ONLY_ACTIVE_ARCH: YES
      DEVELOPMENT_TEAM: $(DEVELOPMENT_TEAM)
      CODE_SIGN_IDENTITY: iPhone Distribution
      CODE_SIGN_STYLE: Manual
      PROVISIONING_PROFILE_SPECIFIER: $(PROVISIONING_PROFILE_SPECIFIER)
      SWIFT_VERSION: $(SWIFT_VERSION)
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      CURRENT_PROJECT_VERSION: $(CURRENT_PROJECT_VERSION)
      OTHER_LDFLAGS: ["$(inherited)", -ObjC]
      FRAMEWORK_SEARCH_PATHS: ["$(inherited)", "$(PROJECT_DIR)"]
    sources: [UnwantedComunication]
    info:
      path: UnwantedComunication/Config/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleIdentifier: $(BUNDLE_IDENTIFIER)
        CFBundleDisplayName: $(PRODUCT_NAME)
        ENVIRONMENT: $(ENVIRONMENT)
        NSExtension: {
          NSExtensionAttributes: {
            ILClassificationExtensionNetworkReportDestination: "https://api-dev.callspam.org/call-report2"
          },
          NSExtensionPointIdentifier: "com.apple.identitylookup.classification-ui",
          NSExtensionMainStoryboard: "MainInterface"
        }
    entitlements:
      path: UnwantedComunication/UnwantedComunication.entitlements
      properties:
        com.apple.developer.associated-domains: [
          "classificationreport:api-dev.callspam.org"
        ]
        com.apple.security.application-groups: [
          "group.br.com.test.call.block.CallSMSBlock"
        ]
    dependencies:
      - package: PhoneNumberKit

  ####################
  # Main app
  ####################
  CallSMSBlock:
    type: application
    platform: iOS
    configFiles:
      Development: CallSMSBlock/Config/dev.xcconfig
      Production: CallSMSBlock/Config/dev.xcconfig
    settings:
      TARGETED_DEVICE_FAMILY: 1
      ASSETCATALOG_COMPILER_APPICON_NAME: $(APP_ICON)
      PRODUCT_NAME: $(PRODUCT_NAME)
      # ONLY_ACTIVE_ARCH: YES
      DEVELOPMENT_TEAM: $(DEVELOPMENT_TEAM)
      CODE_SIGN_IDENTITY: iPhone Distribution
      CODE_SIGN_STYLE: Manual
      PROVISIONING_PROFILE_SPECIFIER: $(PROVISIONING_PROFILE_SPECIFIER)
      SWIFT_VERSION: $(SWIFT_VERSION)
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      CURRENT_PROJECT_VERSION: $(CURRENT_PROJECT_VERSION)
      OTHER_LDFLAGS: ["$(inherited)", -ObjC]
      FRAMEWORK_SEARCH_PATHS: ["$(inherited)", "$(PROJECT_DIR)"]
    sources: [CallSMSBlock]
    resources: [CallSMSBlock/Resources]
    info:
      path: CallSMSBlock/Config/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleIdentifier: $(BUNDLE_IDENTIFIER)
        CFBundleDisplayName: $(APP_DISPLAY_NAME)
        ITSAppUsesNonExemptEncryption: NO
        UIStatusBarStyle: UIStatusBarStyleLightContent
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UISupportedInterfaceOrientations~ipad: [UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UILaunchStoryboardName: LaunchScreen
        UIUserInterfaceStyle: Light
        UIViewControllerBasedStatusBarAppearance: YES
        UIRequiredDeviceCapabilities: [armv7]
        LSRequiresIPhoneOS: YES
        ENVIRONMENT: $(ENVIRONMENT)
    entitlements:
      path: CallSMSBlock/CallSMSBlock.entitlements
      properties:
        com.apple.developer.associated-domains: [
          "classificationreport:api-dev.callspam.org",
          "messagefilter:api-dev.callspam.org"
        ]
        com.apple.security.application-groups: [
          "group.br.com.test.call.block.CallSMSBlock"
        ]
    dependencies:
      - package: PhoneNumberKit
      - target: UnwantedComunication
        embed: true
      - target: MessageFilter
        embed: true
      # - target: CallDirectory
        # embed: true


schemes:
  Development:
    run:
      config: Development
    archive:
      config: Development
    build:
      targets:
        CallSMSBlock: all
      parallelizeBuild: true
      buildImplicitDependencies: true
