name: CallSMSBlock

options:
  developmentLanguage: pt-BR
  
  deploymentTarget:
    iOS: 16.0

packages:
  PhoneNumberKit:
    url: https://github.com/marmelroy/PhoneNumberKit
    exactVersion: 4.0.0

configs:
  Development: debug
  Production: release

targets:
  # Main app
  CallSMSBlock:
    type: application
    platform: iOS
    configFiles:
      Development: Config/dev.xcconfig
      Production: Config/dev.xcconfig
    settings:
      TARGETED_DEVICE_FAMILY: 1
      ASSETCATALOG_COMPILER_APPICON_NAME: $(APP_ICON)
      PRODUCT_NAME: $(PRODUCT_NAME)
      ONLY_ACTIVE_ARCH: YES
      DEVELOPMENT_TEAM: $(DEVELOPMENT_TEAM)
      CODE_SIGN_IDENTITY: iPhone Distribution
      CODE_SIGN_STYLE: Manual
      PROVISIONING_PROFILE_SPECIFIER: $(PROVISIONING_PROFILE_SPECIFIER)
      SWIFT_VERSION: $(SWIFT_VERSION)
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      CURRENT_PROJECT_VERSION: $(CURRENT_PROJECT_VERSION)
      OTHER_LDFLAGS: ["$(inherited)", -ObjC]
      FRAMEWORK_SEARCH_PATHS: ["$(inherited)", "$(PROJECT_DIR)"]
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: [UI]
    sources: [CallSMSBlock]
    resources: [CallSMSBlock/Resources]
    info:
      path: Config/PLists/Info.plist
      properties:
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        CFBundleIdentifier: $(BUNDLE_IDENTIFIER)
        CFBundleDisplayName: $(APP_DISPLAY_NAME)
        ITSAppUsesNonExemptEncryption: NO
        UIStatusBarStyle: UIStatusBarStyleLightContent
        UISupportedInterfaceOrientations: [UIInterfaceOrientationPortrait]
        UISupportedInterfaceOrientations~ipad: [UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UILaunchStoryboardName: LaunchScreen
        UIUserInterfaceStyle: Light
        UIViewControllerBasedStatusBarAppearance: YES
        UIRequiredDeviceCapabilities: [armv7]
        LSRequiresIPhoneOS: YES
        ENVIRONMENT: $(ENVIRONMENT)
        UIBackgroundModes: [remote-notification]
    entitlements:
      path: Superdigital/Superdigital.entitlements
      properties:
        aps-environment: development
        com.apple.developer.associated-domains: [
          "classificationreport:api-dev.callspam.org",
          "messagefilter:api-dev.callspam.org"
        ]
        com.apple.developer.networking.wifi-info: true
    dependencies:
      - package: PhoneNumberKit

schemes:
  Development:
    run:
      config: Development
    archive:
      config: Development
    build:
      targets:
        CallSMSBlock: all
